language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
jobs:
  include:
    - stage: tests
      script: npm test test/court/*.js
      name: "Court"
    - stage: tests
      script: npm test test/registry/*.js
      name: "Registry"
    - stage: tests
      script: npm test test/tree/*.js
      name: "Tree"
    - stage: tests
      script: npm test test/voting/*.js
      name: "Voting"
    - stage: tests
      script: npm test test/*.js
      name: "Others"
